### ISSUE TITLE
Could not make directory in ubuntu

### ISSUE THREAD

**Issue by cuckoo-linux** [simsong/bulk_extractor#100]
I am facing this error while creating wordlist:
cuckoo@cuckoo-OptiPlex-9020:~$ sudo bulk_extractor -e wordlist -o /Desktop/xyz /home/cuckoo/Desktop/Bulk-Extracter/charlie-2009-12-11.E01
**Could not make directory /Desktop/xyz**

**Comment by simsong** [comment]
That’s because you don’t have write access to /. You probably want to use -o ~/Desktop instead.


----
Sent from my phone.

On Feb 8, 2018, at 3:50 AM, cuckoo-linux <notifications@github.com> wrote:

I am facing this error while creating wordlist:
cuckoo@cuckoo-OptiPlex-9020:~$ sudo bulk_extractor -e wordlist -o /Desktop/xyz /home/cuckoo/Desktop/Bulk-Extracter/charlie-2009-12-11.E01
Could not make directory /Desktop/xyz

**Comment by simsong** [comment]
Correct command line:

    $ sudo bulk_extractor -e wordlist -o ~/Desktop/xyz ~/Desktop/Bulk-Extracter/charlie-2009-12-11.E01

**Comment by cuckoo-linux** [comment]
thanks.its working now
