### ISSUE TITLE
Repetitive Exit Code 139 When Running Scan

### ISSUE THREAD

**Issue by Jordanis99** [simsong/bulk_extractor#112]
I'm running Linux Ubuntu 16.04 and when using BEViewer I have selected my user folder for the tool to scan. I have been leaving the default scans checked and only adding the Facebook and Outlook scans. The current command for scan follows:
![Current Scan](https://user-images.githubusercontent.com/48545325/57905838-0e8d4b80-78b7-11e9-99c1-e629738f5e2b.png)
This seems to work successfully until around 15% through the scan, at which point the same error occurs:
![Repetitive Error](https://user-images.githubusercontent.com/48545325/57905857-21a01b80-78b7-11e9-88b1-65313a49fa78.png)
Any idea why?

**Comment by simsong** [comment]
Hi. Two suggestions:

1. Run bulk_extractor from the command line and look at the output.
2. If it crashes, just rerun the command. bulk_extractor should see the partially written dfxml file and start running from where it left off.

Since you are running on a folder of files, it's possible that you have a file in there that's too big to map into your computer's address space.

**Comment by simsong** [comment]
Closing this ticket since we didn't hear anything back.
