### ISSUE TITLE
license of src/scan_outlook.cpp violates license of integrated libpff content

### ISSUE THREAD

**Issue by joachimmetz** [simsong/bulk_extractor#143]
If content was copied from libpff/libpff_encryption.c into https://github.com/simsong/bulk_extractor/blob/master/src/scan_outlook.cpp

This violates the original license https://github.com/libyal/libpff/blob/master/libpff/libpff_encryption.c, since it can only be integrated directly into LGPLv3 or GPLv3 licensed source. Also see: https://www.gnu.org/licenses/lgpl-3.0.en.html

Recommended fix:
* Move libpff LGPLv3 licensed material into a separate file
* update LICENSES.md

**Comment by joachimmetz** [comment]
I'll prep a PR to address this

**Comment by simsong** [comment]
Thanks for pointing this out. 
It appears that the line was not linked because `libpff_encryption_compressible` is declared as `static`, so the symbol is not externally visible:

https://github.com/libyal/libpff/blob/34c48fb28e0d28f829d801d7bce646ef8eebe6d4/libpff/libpff_encryption.c#L38

I suppose this could be included with an `#include`, which did not occur to me at the time.

Your recommended option is fine.

Another option would be to simply assert that `libpff_encryption_compressible` cannot be covered under copyright law, because it is a table of numbers that was extracted from another program, and that is one of the things that specifically *cannot* be copyrighted. I'm not making that claim here, but that is my reading of US law and the substantial body of work on this topic. However, it is not an argument that is useful, given that the option to simply [https://github.com/libyal/libpff/blob/master/libpff/libpff_encryption.c](https://github.com/libyal/libpff/blob/master/libpff/libpff_encryption.c) exists.

**Comment by simsong** [comment]
> I'll prep a PR to address this

Way ahead of you... https://github.com/libyal/libpff/pull/89

**Comment by joachimmetz** [comment]
I would recommend making the changes in bulk extractor. It is fine to have the file in bulk extractor, it just needs to retain its license. We can always indicated copied with permission.

**Comment by simsong** [comment]
Oh, okay. I'll kill my fork and follow your recommended approach.

**Comment by joachimmetz** [comment]
Issue addressed, closing
