### ISSUE TITLE
Post source code release including 'configure' script.

### ISSUE THREAD

**Issue by bgrundy** [simsong/bulk_extractor#353]
[PR #352](https://github.com/simsong/bulk_extractor/pull/352) appears to indicate that there's a source distribution of BE somewhere with a configure script.  I cannot find a live link to it anywhere.  The link on the Code/About page (http://downloads.digitalcorpora.org/downloads/bulk_extractor) does not appear to have 2.0.0, and the link on the Wiki/Downloads page of this project results in a 404 error ( and still points to https://github.com/fedorie/gitflow/releases/download/0.4/bulk_extractor64_1.1.2.zip).  

Can you provide a link to the source tarball with a configure script?  I'd like to create a distribution package without requiring a bootstrap.  Most of the Github projects I do this with include configure scripts in the  Code/Releases tarballs, which does not seem to be the case here.  Many thanks.

**Comment by simsong** [comment]
I have updated https://github.com/simsong/bulk_extractor/releases/tag/v2.0.0 so that it now includes `bulk_extractor-2.0.0.tar.gz`. 

I concur with you that many people who use GitHub may not understand the need to clone a repo with the `--recursive` flag and may not understand how to use autotools to create the `configure` script.
