### ISSUE TITLE
Provide a tarball that includes all submodules

### ISSUE THREAD

**Issue by jgru** [simsong/bulk_extractor#368]
Dear Simson,

I want to request kindly to supply a tarball of `bulk_extractor` that includes all submodules needed for building the code. Providing such an "all-inclusive archive" would ease distributing (and eventual packaging) of `bulk_extractor` significantly.

This issue is addressed in #367.

Best regards, 
jgru

**Comment by simsong** [comment]
Hi. The file that you request is in the "Releases" location:
https://github.com/simsong/bulk_extractor/releases/tag/v2.0.0

**Comment by jgru** [comment]
> Hi. The file that you request is in the "Releases" location: https://github.com/simsong/bulk_extractor/releases/tag/v2.0.0

Thanks for your reply. Sorry, should have looked better. 
I looked only into [v2.0.0.tar.gz](https://github.com/simsong/bulk_extractor/archive/refs/tags/v2.0.0.tar.gz)  and assumed the other tar.gz is the compiled version...my bad.

Maybe the Github workflow I sent as PR is of interest anyways.

**Comment by simsong** [comment]
Hi. Thank you for the suggestion.

I understand what your patch does, but I do not understand the purpose. We have releases that are included in the "Releases" location. It seems that your patch would create a tarball of the source with the modules. This is useful for people who do not know to add the `--recurse-submodules` command to the `git clone` command. 

But that tarball will not include a `configure` command. I will then get complaints that there is no `configure` command from people who don't know how to use autoconf. I've previously had such complaints, and that's why we host the autoconf-generated release.

I think that it's a good idea for usability to have the release automatically created. Would you like to try to modify the pull release so that it does that?

I should also fix the downloads location on DigitalCorpora. I'll add an issue for that.

Are you interested in helping with other aspects of `bulk_extractor`?

**Comment by jgru** [comment]
Hi Simson, 

> I understand what your patch does, but I do not understand the purpose. We have releases that are included in the "Releases" location. It seems that your patch would create a tarball of the source with the modules. This is useful for people who do not know to add the `--recurse-submodules` command to the `git clone` command.
> 
> But that tarball will not include a `configure` command. I will then get complaints that there is no `configure` command from people who don't know how to use autoconf. I've previously had such complaints, and that's why we host the autoconf-generated release.
> 

My intention was to provide a workflow-driven mechanism to provide all necessary source files. 
Primarily, I am interested in such a tarball since I want to package `bulk_extractor` for Debian's package archives (and Debian-based OSes, like Ubuntu). Running the autoconf-toolchain could then be part of the package building. Still it is better to provide a autoconf- generated tarball of course. I didn't think about that obvious solution, so thanks for the hint. 

> I think that it's a good idea for usability to have the release automatically created. Would you like to try to modify the pull release so that it does that?
> 

Good to hear. I modified my PR (#367) accordingly. It now uses `make dist` to generate the tarball and uploads it under the release section. If you have any suggestions on how to improve it, please let me know.  (E.g., we could change it to produce a tarball on each push on the master-branch named as `bulk_extractor-$VERSION-$COMMIT_SHA.tar.gz`) 

> I should also fix the downloads location on DigitalCorpora. I'll add an issue for that.
> 
> Are you interested in helping with other aspects of `bulk_extractor`?

I am interested indeed. If my time constraints permit to do so, I will monitor the "Milestones" section and issues. 
The next task is to package `bulk_extractor` for Debian, I hope this is in your best interest.

Thanks for your openness regarding contributions.

**Comment by simsong** [comment]
Hm. Milestones. I guess I should create some...

**Comment by simsong** [comment]
Release 2.1 is posted.
