### ISSUE TITLE
PII not being picked up by scanner.

### ISSUE THREAD

**Issue by edp05373** [simsong/bulk_extractor#82]
v1.5.5 Windows install x64:

Not detecting social security numbers in a RAM DD image for pii.txt.

**Comment by simsong** [comment]
Please post your command line and a sample disk image.

**Comment by edp05373** [comment]
Hi Simon. I was using the bulk extractor GUI 1.5.5 for Windows. I found
SS#, but only my luck when browsing thru the telephone artifacts. The
PII.txt file was empty.

I don't have a sample ram image to give right now. This was on a real case.

Thanks. Love the tool.


Ed

**Comment by simsong** [comment]
Ed,

I don’t want your disk image, I want you to make a tiny (5KiB) test file containing a fake SSN in the same format as the one you were trying to find. If it was in a file made by Word or Excel, you should try to make it with the same application.

I’m glad you found your SSN.

**Comment by simsong** [comment]
Ed,

I don’t want your disk image, I want you to make a tiny (5KiB) test file containing a fake SSN in the same format as the one you were trying to find. If it was in a file made by Word or Excel, you should try to make it with the same application.

** This is the kind of explicit test data that we need to have in order to find and correct problems with bulk_extractor. Otherwise we have a complaint, but there is no way to take action on it. **

I’m glad you found your SSN.

**Comment by edp05373** [comment]
Hi Simon. I made a simple text file with some social security # formats and
still didn't pick them up.

Just wanted to let you know.

Ed

**Comment by simsong** [comment]
That's great!

If you could post the small disk image, and the output, I'll take a look!

**Comment by simsong** [comment]
What are you specifying for ssn_mode ?

**Comment by simsong** [comment]
Can't fix this without a test case.
